// pages/api/evaluate.js
import Groq from "groq-sdk";

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).end();
  const { answer } = req.body;
  if (!answer) return res.status(400).json({ error: "missing answer" });

  try {
    const prompt = `You are an assistant that evaluates whether the following answer appears written/spoken by a human or generated by an AI model.
Return only JSON with fields: humanPercent (0-100 integer), aiPercent (0-100 integer), briefReason (one-line).
Answer: """${answer}"""`;

    const resp = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant",
      messages: [{ role: "user", content: prompt }],
    });

    let data = { humanPercent: 50, aiPercent: 50, briefReason: "" };
    try {
      const maybeJson = resp.choices[0].message.content.match(/\{[\s\S]*\}/);
      if (maybeJson) data = JSON.parse(maybeJson[0]);
      else data.briefReason = resp.choices[0].message.content;
    } catch (err) {
      data.briefReason = resp.choices[0].message.content;
    }

    return res.status(200).json(data);
  } catch (err) {
    console.error("Evaluation error:", err);
    return res.status(500).json({ error: "evaluation failed" });
  }
}
